version: "3.9"

services:
  kata-akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kata-kafka:29092"
                security.protocol: PLAINTEXT
    ports:
      - "3000:8080"
    depends_on:
      - kata-kafka_init

  kata-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'

  kata-kafka:
    image: confluentinc/cp-kafka:7.5.0
    volumes:
      - kafka-data:/var/lib/kafka/data:Z
    depends_on:
      - kata-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_ZOOKEEPER_CONNECT: 'kata-zookeeper:2181'
      KAFKA_NUM_PARTITIONS: '12'
      KAFKA_COMPRESSION_TYPE: 'gzip'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kata-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: '9091'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'


  # Attention : Ce bloc doit être aligné avec kata-kafka ci-dessus (2 espaces)
  kata-kafka_init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kata-kafka
    restart: "no"
    command:
      - /bin/sh
      - -c
      - |
        echo 'Waiting for Kafka to be ready...'
        until kafka-topics --bootstrap-server kata-kafka:29092 --list > /dev/null 2>&1; do 
          echo "Kafka is not ready yet... sleeping 2s"
          sleep 2
        done
        
        echo 'Kafka is ready! Creating topic...'
        kafka-topics --bootstrap-server kata-kafka:29092 --topic my-first-topic --create --partitions 3 --replication-factor 1 --if-not-exists
        
        echo 'Successfully created the following topics:'
        kafka-topics --bootstrap-server kata-kafka:29092 --list

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local